[package]
name = "eightyeighty"
version = "0.1.0"
authors = ["Julian Gautier <juliangautier@juliangautier.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.1"